### ISSUE TITLE
大神，更新数据库时经常失败，提示如下，请问如何解决？需要增加配置文件吗？

### ISSUE THREAD

**Issue by jliveusa** [peter-tank/luci-app-dnscrypt-proxy2#3]
dnscrypt-proxy -json --list-all > /usr/share/dnscrypt-proxy/running.json
[2020-01-18 08:48:17] [FATAL] Unable to load the configuration file [dnscrypt-proxy.toml] -- Maybe use the -config command-line switch?

**Comment by peter-tank** [comment]
You are failed in update the nodes lists?
Try the latest version, update nodes list manually not needed anymore (https://github.com/peter-tank/luci-app-dnscrypt-proxy2/releases/tag/v2.0.36-1)
https://github.com/peter-tank/luci-app-dnscrypt-proxy2/blob/7c11053d048bc77f7147e79a6546210a7ee10fb0/files/luci/controller/dnscrypt-proxy.lua#L60-L65
Make sure wget installed `/usr/bin/wget-ssl`, is needed.
If also fails, you should update nodes list under proxy first in the first initial.

**Comment by peter-tank** [comment]
You can also runs `/etc/init.d/dnscrypt-proxy_resolvers public-resolvers`, to manualy download and  parse the `public-resolvers` subscripition to configure, if uci tracking fails.
