### ISSUE TITLE
if dnscrypt-proxy is already installed, opkg install fails

### ISSUE THREAD

**Issue by checkraisefold** [peter-tank/luci-app-dnscrypt-proxy2#4]
```
Collected errors:
 * check_data_file_clashes: Package luci-app-dnscrypt-proxy2 wants to install file /etc/init.d/dnscrypt-proxy
	But that file is already provided by package  * dnscrypt-proxy2
 * opkg_install_cmd: Cannot install package `luci-app-dnscrypt-proxy2.
```
epic fun time

**Comment by checkraisefold** [comment]
nvm intial release just doesn't install
https://i.vgy.me/AxDo2n.png

**Comment by peter-tank** [comment]
Your package "dnscrypt-proxy2" shares the same initscript `/etc/init.d/dnscrypt-proxy`
1. `mv $(which dnscrypt-proxy) /usr/sbin/ &&opkg remove dnscrypt-proxy2`
1. `opkg install luci-app-dnscrypt-proxy2.ipk`

Go to dnscrypt-proxy2 UI:
1. update `public-resolvers`, there should be 4 files under `/usr/share/dnscrypt-proxy/` if everything goes right.
1. enable dnscrypt-proxy2 in proxy settings
1. force a reload.

**Comment by peter-tank** [comment]
> nvm intial release just doesn't install
> https://i.vgy.me/AxDo2n.png

Allready installed to your system.
Take a look into LUCI interfaces changes.

1. check and install dnscrypt-proxy2 binary to `/usr/sbin/`, or `opkg download dnscrypt-proxy2&&tar xzvf xxx.ipk&&tar xzvf data.tar.gz&&mv dnscrypt-proxy /usr/sbin/`
