### ISSUE TITLE
Insufficient permissions to read UCI configuration

### ISSUE THREAD

**Issue by firewire10000** [peter-tank/luci-app-dnscrypt-proxy2#8]
The newer builds of OpenWrt have ACL support to allow different users and user groups access various LuCI apps.

Currently if i go to the DNSCrypt Proxy on the web-GUI i get this message 'Insufficient permissions to read UCI configuration'

**Comment by peter-tank** [comment]
A Quick Fix: [FYI](https://forum.openwrt.org/t/insufficient-permissions-to-read-uci-configuration/61694/7)
```shell
RPCD_FILE=/usr/share/rpcd/acl.d/luci-app-dnscrypt-proxy2.json
cat > $RPCD_FILE <<EOF
{
	"luci-app-dnscrypt-proxy2": {
		"description": "Grant UCI access for luci-app-dnscrypt-proxy2",
		"read": {
			"uci": [ "dnscrypt-proxy" ]
		},
		"write": {
			"uci": [ "dnscrypt-proxy" ]
		}
	}
}
EOF
```
